type Product = {
  id: number;
  name: string;
  category: string;
  price: number;
  inStock: number;
  description: string;
  image: string;
  saved: boolean;
  quantity: number;
};

export const Products: Product[] = [
  {
    id: 0,
    name: "Smart TV",
    category: "electronics",
    price: 158.57,
    inStock: 10,
    description: "32-inch Flat Screen 720p Smart LED TV",
    image: "smart_tv.jpg",
    saved: false,
    quantity: 1,
  },
  {
    id: 1,
    name: "Camera",
    category: "electronics",
    price: 1299,
    inStock: 10,
    description:
      "Olympus OM-D E-M5 Mark III Silver Body with Black M.Zuiko Digital ED 12-45mm F4.0 PRO Lens Kit",
    image: "camera.jpg",
    saved: false,
    quantity: 1,
  },
  {
    id: 2,
    name: "Laptop",
    category: "electronics",
    price: 449.81,
    inStock: 10,
    description:
      "Apple MacBook Pro 13-inch 2.3GHz Core i5, 256GB - Space Gray - 2017",
    image: "laptop.jpg",
    saved: false,
    quantity: 1,
  },
  {
    id: 3,
    name: "Phone",
    category: "electronics",
    price: 749.99,
    inStock: 10,
    description: "Apple iPhone 13, 128GB, Midnight - Verizon",
    image: "phone.jpg",
    saved: false,
    quantity: 1,
  },
  {
    id: 4,
    name: "Headphone",
    category: "electronics",
    price: 199.99,
    inStock: 10,
    description: "Beats by Dr. Dre - Beats Solo3 Wireless Headphones - Gold",
    image: "headphone.jpg",
    saved: false,
    quantity: 1,
  },
  {
    id: 5,
    name: "Nintendo",
    category: "electronics",
    price: 299,
    inStock: 10,
    description: "Nintendo Switch with Neon Blue and Neon Red Joy‑Con",
    image: "nintendo.jpg",
    saved: false,
    quantity: 1,
  },
  {
    id: 6,
    name: "Game Controller",
    category: "electronics",
    price: 59.99,
    inStock: 10,
    description:
      "DualShock 4 Wireless Controller for PlayStation 4 - Jet Black",
    image: "game_controller.jpg",
    saved: false,
    quantity: 1,
  },
  {
    id: 7,
    name: "Smart Watch",
    category: "electronics",
    price: 84.99,
    inStock: 10,
    description:
      "Amazfit GTS 2 Mini Smart Watch GPS Fitness Tracker for Men Women, Alexa Built-in, 14 Days Battery Life, 70+ Sports Modes, Blood Oxygen Heart Rate Sleep Monitor, AMOLED Screen, 5 ATM Waterproof-Black",
    image: "smart_watch.jpg",
    saved: false,
    quantity: 1,
  },
  {
    id: 8,
    name: "Washing Machine",
    category: "electronics",
    price: 192.12,
    inStock: 10,
    description:
      "Pyle XPB20-288S PYRPUCWM22 Compact & Portable Washer & Dryer, 0, White",
    image: "washing_machine.jpg",
    saved: false,
    quantity: 1,
  },
  {
    id: 9,
    name: "Pressing Iron",
    category: "electronics",
    price: 149.99,
    inStock: 10,
    description:
      "Rowenta DW9280 Digital Display Steam Iron, Stainless Steel Soleplate, 1800-Watt, 400-Hole, Blue",
    image: "pressing_iron.jpg",
    saved: false,
    quantity: 1,
  },
  {
    id: 10,
    name: "Men's Hoodie",
    category: "men clothing",
    price: 29.99,
    inStock: 10,
    description:
      "Gesean Men's Novelty Color Block Pullover Fleece Hoodie Long Sleeve Casual Sweatshirt with Pocket",
    image: "men_hoodie.jpg",
    saved: false,
    quantity: 1,
  },
  {
    id: 11,
    name: "Men's Sweatpants",
    category: "men clothing",
    price: 10.99,
    inStock: 10,
    description: "Fruit of the Loom Men's Eversoft Fleece Sweatpants & Joggers",
    image: "men_sweatpants.jpg",
    saved: false,
    quantity: 1,
  },
  {
    id: 12,
    name: "Men's Underwear",
    category: "men clothing",
    price: 64.5,
    inStock: 10,
    description:
      "Calvin Klein Men's Underwear Cotton Stretch 5-Pack Boxer Brief",
    image: "men_underwear.jpg",
    saved: false,
    quantity: 1,
  },
  {
    id: 13,
    name: "Men's Denim Jacket",
    category: "men clothing",
    price: 39.99,
    inStock: 10,
    description:
      "Jean Jacket for Men, Fashion Mens Denim Jacket Washed Classic Casual Distressed Ripped Slim Fit Trucker Jacket",
    image: "men_denim_jacket.jpg",
    saved: false,
    quantity: 1,
  },
  {
    id: 14,
    name: "Men's Cargo Pant",
    category: "men clothing",
    price: 30.99,
    inStock: 10,
    description:
      "Romwe Men's Flap Pocket Drawstring Elastic Waist Letter Graphic Street Cargo Pants",
    image: "men_cargo_pants.jpg",
    saved: false,
    quantity: 1,
  },
  {
    id: 15,
    name: "Men's Cargo Short",
    category: "men clothing",
    price: 27.99,
    inStock: 10,
    description:
      "AUTIWITUA Men's Waterproof Tactical Shorts Outdoor Cargo Shorts, Lightweight Quick Dry Breathable Hiking Fishing Cargo Shorts",
    image: "men_cargo_short.jpg",
    saved: false,
    quantity: 1,
  },
  {
    id: 16,
    name: "Men's Boots",
    category: "men clothing",
    price: 49.99,
    inStock: 10,
    description:
      "CC-Los Hiking Shoes for Men Waterproof Lightweight All Day Comfort",
    image: "men_shoe.jpg",
    saved: false,
    quantity: 1,
  },
  {
    id: 17,
    name: "Men's Sunshades",
    category: "men clothing",
    price: 19.99,
    inStock: 10,
    description:
      "Polarized Sunglasses for Men and Women Matte Finish Sun glasses Color Mirror Lens 100% UV Blocking (3 Pack)",
    image: "men_glasses.jpg",
    saved: false,
    quantity: 1,
  },
  {
    id: 18,
    name: "Men's T-shirt",
    category: "men clothing",
    price: 19.99,
    inStock: 10,
    description:
      "Romwe Men's Hawaiian Shirt Button Down Short Sleeve Tropical Casual Beach Shirt Tops",
    image: "men_tshirt.jpg",
    saved: false,
    quantity: 1,
  },
  {
    id: 19,
    name: "Men's Jean Pants",
    category: "men clothing",
    price: 34.99,
    inStock: 10,
    description: "Dockers Men's Straight Fit Jean Cut All Seasons Tech Pants",
    image: "men_jeans.jpg",
    saved: false,
    quantity: 1,
  },
  {
    id: 20,
    name: "Women's Hoodie",
    category: "women clothing",
    price: 29.99,
    inStock: 10,
    description:
      "GIVON Womens Comfortable Long Sleeve Lightweight Pullover Hoodie With Kanga Pocket(XS~4XL)",
    image: "women_hoodie.jpg",
    saved: false,
    quantity: 1,
  },
  {
    id: 21,
    name: "Women's Sweatpants",
    category: "women clothing",
    price: 19.99,
    inStock: 10,
    description:
      "DIBAOLONG Womens Joggers with Pockets Loose Yoga Sweatpants Casual Harem Workout Lounge Pants",
    image: "women_sweatpants.jpg",
    saved: false,
    quantity: 1,
  },
  {
    id: 22,
    name: "Lingerie",
    category: "women clothing",
    price: 45.99,
    inStock: 10,
    description:
      "Avidlove Lingerie for Women Lace Babydoll Sleepwear Boudoir Outfits Plus Size Langeray XS-5XL",
    image: "women_underwear.jpg",
    saved: false,
    quantity: 1,
  },
  {
    id: 23,
    name: "Women's Denim Jacket",
    category: "women clothing",
    price: 45.99,
    inStock: 10,
    description:
      "Sidefeel Womens Basic Long Sleeve Distressed Button Down Denim Jean Jackets",
    image: "women_denim_jacket.jpg",
    saved: false,
    quantity: 1,
  },
  {
    id: 24,
    name: "Women's Cargo Pants",
    category: "women clothing",
    price: 25.98,
    inStock: 10,
    description:
      "CREATMO US Women's Lightweight Quick Dry Cargo Hiking Pants Athletic Joggers",
    image: "women_cargo_pants.jpg",
    saved: false,
    quantity: 1,
  },
  {
    id: 25,
    name: "Women's Casual Shorts",
    category: "women clothing",
    price: 27.99,
    inStock: 10,
    description:
      "MASKERT Women's Hiking Cargo Shorts Quick Dry Athletic Golf Shorts 5 Inches Lightweight Running Summer Casual Shorts",
    image: "women_shorts.jpg",
    saved: false,
    quantity: 1,
  },
  {
    id: 26,
    name: "Women's Boots",
    category: "women clothing",
    price: 139.95,
    inStock: 10,
    description: "Women's Luxury leather Chelsea boots",
    image: "women_boots.jpg",
    saved: false,
    quantity: 1,
  },
  {
    id: 27,
    name: "Women's Glasses",
    category: "women clothing",
    price: 14.98,
    inStock: 10,
    description:
      "Przene set of Blue Light Blocking Glasses, Retro Semi Rimless UV400 Clear Lens Computer Eyewear For Women.",
    image: "women_glasses.jpg",
    saved: false,
    quantity: 1,
  },
  {
    id: 28,
    name: "Fitted Crop Top",
    category: "women clothing",
    price: 13.99,
    inStock: 10,
    description:
      "KLOTHO Lightweight Crop Tops Slim Fit Stretchy Workout Shirts for Women",
    image: "women_tshirt.jpg",
    saved: false,
    quantity: 1,
  },
  {
    id: 29,
    name: "Women's  Jean Pants",
    category: "women clothing",
    price: 41.99,
    inStock: 10,
    description: "WeWoreWhat Women's Dani Boyfriend Jeans",
    image: "women_jeans.jpg",
    saved: false,
    quantity: 1,
  },
];
